//错误信息
#define STRING_OUT_OF_BOUND "     ERROR!     "
//基础信息
#define LINE_MAX_LENGTH 16
#define DATE_TIME_DIGIT_COUNT 6
//时钟
#define MIN_YEAR 1997
#define MAX_YEAR 9999
#define MIN_MONTH 1
#define MAX_MONTH 12
#define MIN_DAY 1
#define MAX_DAY 31
#define MIN_SECOND 0
#define MAX_SECOND 59
#define MIN_MINUTE 0
#define MAX_MINUTE 59
#define MIN_HOUR 0
#define MAX_HOUR 23
#define MONTH_DAY_ARR {31,28,31,30,31,30,31,31,30,31,30,31}
#define FEBRUARY_LONG 29
#define FEBRUARY_SHORT 28
#define DEFAULT_DATE "   2016-02-28"
#define DEFAULT_TIME "    23:59:55"

#define YEAR_SEQ 1
#define MONTH_SEQ 2
#define DAY_SEQ 3
#define WEEK_SEQ 4
#define HOUR_SEQ 5
#define MINUTE_SEQ 6
#define SECOND_SEQ 7

//显示屏各个位的显示位置
#define BASIC_POSITION 0x80
#define SECOND_LINE_FIRST_POSITION BASIC_POSITION+0x40
#define YEAR_ONE_POSITION BASIC_POSITION+0x03
#define YEAR_TWO_POSITION YEAR_ONE_POSITION+0x01
#define YEAR_THREE_POSITION  YEAR_TWO_POSITION+0x01
#define YEAR_FOUR_POSITION YEAR_THREE_POSITION+0x01
#define MONTH_HIGH_POSITION BASIC_POSITION+0x08
#define MONTH_LOW_POSITION MONTH_HIGH_POSITION+0x01
#define DAY_HIGH_POSITION BASIC_POSITION+0x0b
#define DAY_LOW_POSITION DAY_HIGH_POSITION+0x01
#define HOUR_HIGH_POSITION SECOND_LINE_FIRST_POSITION+0x04
#define HOUR_LOW_POSITION HOUR_HIGH_POSITION+0x01
#define MINUTE_HIGH_POSITION SECOND_LINE_FIRST_POSITION+0x07
#define MINUTE_LOW_POSITION MINUTE_HIGH_POSITION+0x01
#define SECOND_HIGH_POSITION SECOND_LINE_FIRST_POSITION+0x0a
#define SECOND_LOW_POSITION SECOND_HIGH_POSITION+0x01

//每个位置上的最大值和最小值
#define POSITION_ARRAY {YEAR_ONE_POSITION,YEAR_TWO_POSITION,YEAR_THREE_POSITION,YEAR_FOUR_POSITION,MONTH_HIGH_POSITION,MONTH_LOW_POSITION,DAY_HIGH_POSITION,DAY_LOW_POSITION,HOUR_HIGH_POSITION,HOUR_LOW_POSITION,MINUTE_HIGH_POSITION,MINUTE_LOW_POSITION,SECOND_HIGH_POSITION,SECOND_LOW_POSITION}
#define POSITION_ARRAY_LENGTH 14
#define POSITION_MAX_VALUE_ARRAY {9,9,9,9,1,9,3,9,2,9,5,9,5,9}
#define POSITION_MIN_VALUE_ARRAY {1,0,0,0,0,0,0,0,0,0,0,0,0,0}